# Generated by Django 5.0.2 on 2024-02-29 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0002_customtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='permissions',
        ),
        migrations.AddField(
            model_name='team',
            name='permissions',
            field=models.JSONField(default=list),
        ),
    ]
