# Generated by Django 5.0.2 on 2024-02-27 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='unique_id',
        ),
    ]
